### ISSUE TITLE
Wher could I finde Windows XP drivers?

### ISSUE THREAD

**Issue by Mannshoch** [virtio-win/virtio-win-guest-tools-installer#16]
I need to virtualize a Windows XP and may a Windows 98.
Is there also a Driver set for that case? The current Guest tools could not be installed on Windows XP

**Comment by vrozenfe** [comment]
XP drivers are not included into installer (.MSI) but still available in the latest virtio-win package 
For example WinXP Balloon binaries can be found on virtio-win.iso image 
(https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/virtio-win-0.1.190.iso
) under /Balloon/xp subdirectory. 
Boot time drivers are also included into .vfd (virtual floppy disk) images.

VxD virtio-win  drivers for Windows 95/98/Me  were never supported.

Vadim.

**Comment by Mannshoch** [comment]
Thanks!
