### ISSUE TITLE
VirtIO-FS Service's `Name` and `DisplayName` seem inverted

### ISSUE THREAD

**Issue by jwatt** [virtio-win/virtio-win-guest-tools-installer#23]
https://github.com/virtio-win/virtio-win-guest-tools-installer/blob/9add9b4403310b079646973f57cd1839998d0229/virtio-win-drivers-installer/Drivers/viofs/viofs_extras.wxi#L25-L27

Opening the Windows `Services` app and looking at other Windows services (particularly MS Windows own services, but also the `QEMU Guest Agent` and `Spice Agent` services) it seems like the values for `Name` and `DisplayName` in the file above are inverted. Would a pull request to switch their values around be accepted?

**Comment by jwatt** [comment]
Most services also seem to have helpful descriptions. How about also changing the description to:

"Enables Windows virtual machines to access directories on the host that have been shared with it using VirtIO-FS."

**Comment by YanVugenfirer** [comment]
@jwatt thank you for your comment.
Please send PR and let’s have discussion as part of the PR.

Please didn’t forget to have “Signed-off-by:” in the commit message.
