### ISSUE TITLE
using virtio-win-guest-tools.exe uninstall drivers, why vioscsi and viostor are not uninstalled?

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/virtio-win-guest-tools-installer#39]

**Comment by ChendongSun** [comment]
using virtio-win-guest-tools.exe uninstall drivers, why vioscsi and viostor are not uninstalled? and dirver.sys is still in C:/Windows/system32/drivers

**Comment by vrozenfe** [comment]
@ChendongSun 
Not sure what dirver.sys is,
but both vioscsi and viostar are explicitly marked as permanent
https://github.com/virtio-win/virtio-win-guest-tools-installer/blob/master/virtio-win-drivers-installer/Drivers/vioscsi/vioscsi.wxi#L8
https://github.com/virtio-win/virtio-win-guest-tools-installer/blob/master/virtio-win-drivers-installer/Drivers/viostor/viostor.wxi#L8

It was done purposely to prevent situation when VM becomes unbootable or loses a virtio volume during 
the next boot after uninstalling virtio storage driver. 

Best,
Vadim.
