### ISSUE TITLE
 Driver uninstall and reinstall multiple times will fail on Windows Server 2022

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/virtio-win-guest-tools-installer#42]
I built my NetKVm drivers via kvm-guest-drivers-windows. But on Windows Server 2022, after multiple uninstalls and reinstalls, my network devices are not working. Just replace NetKVm.sys and NetKVm.cat in virtio-win-0.1.229-1.noarch.rpm and it will still work fine on Windows Server 2022.

**Comment by YanVugenfirer** [comment]
How are you reinstalling the driver?
I suggest using a clean VM image.

**Comment by ChendongSun** [comment]
I reinstalled using virtio-win-gt-x64.msi on clean VM image，and it works fine if I install it manually with NetKVM.inf

**Comment by YanVugenfirer** [comment]
Sorry, so the installation from MSI doesn't work on clean VM image?

**Comment by ChendongSun** [comment]
I found out that the problem was introduced by this patch
https://github.com/virtio-win/kvm-guest-drivers-windows/commit/c985a6ca1bea49b883a07a6d5bc3932d51613bce
