### ISSUE TITLE
a program run as part of the setup did not finish as expected

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/virtio-win-guest-tools-installer#43]
There is an installation exception on my environment, what should I do to fix it
![image](https://github.com/virtio-win/virtio-win-guest-tools-installer/assets/19245872/f0a40812-1165-4dcf-ac9c-a61d164ce08b)

**Comment by ChendongSun** [comment]
![image](https://github.com/virtio-win/virtio-win-guest-tools-installer/assets/19245872/37efe6fc-b213-4ca0-86d7-d740f0ee1617)
![image](https://github.com/virtio-win/virtio-win-guest-tools-installer/assets/19245872/9c23291b-c0f3-4ea8-9a3f-fb64a98e4717)
After uninstalling qga, the vss service is still causing the new qga to fail to install

**Comment by ChendongSun** [comment]
"cmd.exe /c "[qemu_ga_directory]qemu-ga.exe" -s vss-uninstall" is not work
![image](https://github.com/virtio-win/virtio-win-guest-tools-installer/assets/19245872/4708ec6d-b8fd-4432-9d73-2358eda9bbcd)

**Comment by YanVugenfirer** [comment]
Can you remove the service from the service manager?

**Comment by ChendongSun** [comment]
I deleted HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\QEMU Guest Agent VSS provider in the regedit, and then restarted the machine.but the problem still exists

**Comment by ChendongSun** [comment]
This is the error log for installing qemu-ga.msi.
[1.log](https://github.com/virtio-win/virtio-win-guest-tools-installer/files/11778849/1.log)

**Comment by ChendongSun** [comment]
This problem may be related to the installation process destroy, which can be fixed by this method：
[com+无法与Miscrsoft分布式事务协调程序交谈](https://answers.microsoft.com/zh-hans/windows/forum/all/%e7%82%b9%e5%87%bbcom%e5%ba%94%e7%94%a8%e7%a8%8b/7fb05f31-f1b4-4528-9a91-6439af6cfd94)
