### ISSUE TITLE
What are the artifacts of this repo?

### ISSUE THREAD

**Issue by rgl** [virtio-win/virtio-win-guest-tools-installer#5]
Can you please describe in the README.md what are the artifacts produced by this repository? And where should we get them (preferably at this project release page)?

**Comment by rgl** [comment]
Will it end up in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.173-2/virtio-win-0.1.173.iso, which is created by https://github.com/crobinso/virtio-win-pkg-scripts, is that correct?

**Comment by Gal-Zaidman** [comment]
yes the iso which is created contains the msis generated from this repo
