### ISSUE TITLE
ocasionally fail to install qemu-ga.msi

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/virtio-win-guest-tools-installer#53]
ocasionally fail to install qemu-ga.msi
There is a problem with this Windows Installer package.A program run as part of the setup did not finish as expected.Contact your support personnel or package vendor.

![image](https://github.com/virtio-win/virtio-win-guest-tools-installer/assets/19245872/4fb986e2-9223-480a-82e9-7b44a989b82b)

1、try to cmd.exe \c  {qemu-ga-path}\qemu-ga.exe -s install
QGA VSS provider is already installed.(Error：80004004) ？？？？

2、try to cmd.exe \c {qemu-ga-path}\qemu-ga.exe -s uninstall
CocreateInstance.(Error: 80070005)????
Removing COM+ Application:Qemu Guest Agent VSSProvider
Failed to pColl->SaveChanges. (Error:80070005)?????

No handle to service control manager (Error:5)?????

How to fix this problem

**Comment by kostyanf14** [comment]
Hi @ChendongSun,

Can you please provide a full installation log?
If you use virtio-win-guest-tools.exe run from the command line `virtio-win-guest-tools.exe  /install /norestart /log log.txt` and share all generated logs. There will be multiple files log_<number>_*.txt please attach all of them.

if you use `qemu-ga.msi` run  from the command line `msiexec /i "qemu-ga.msi" /L*V "log.txt"`
