### ISSUE TITLE
When i using windbug troubleshoots the memory leak problem of qemu-ga.exe

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/virtio-win-guest-tools-installer#55]
When i using windbug troubleshoots the memory leak problem of qemu-ga.exe, it shows that a symbol file is required. Then how to generate symbol files？

gflags.exe  /I  qemu-ga.exe  +ust
（run qemu-ga.exe）
umdh.exe  -pn:qemu-ga.exe  -f:C:\log_11.txt
umdh.exe  -pn:qemu-ga.exe  -f:C:\log_12.txt
umdh.exe  C:\log_11.txt  C:\log_12.txt  -f:C:\log_r1.txt

**Comment by YanVugenfirer** [comment]
You can use https://github.com/rainers/cv2pdb.
`cv2pdb qemu-ga.exe`
