### ISSUE TITLE
In what situations would an installation of qemu-ga-x86_64.msi prompt a pop-up message for a reboot?

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/virtio-win-guest-tools-installer#59]
Why is it that sometimes when I overwriting install qemu-ga-x86_64.msi, a pop-up message prompts me for a reboot and sometimes it does not?
The message is as follows:
You must restart you system for the configuration changes made to Qemu guest agent to take effect.Click Yes to restart now or No if you plan to manually restart later

**Comment by YanVugenfirer** [comment]
Good question that needs the investigation.
I would guess that sometimes the servers is not stopped during uninstall for some reason.
@kostyanf14 ?

**Comment by 6-dehan** [comment]
The registry and system services will be affected during the installation process, but the possibilities still exist:

- Some changes may not take effect until the next system startup, but the installer may not explicitly ask for a restart during the installation process, In this case, the system will apply the changes on the next startup. 

- Or the changes during installation will not interrupt critical processes or services running on the system, and a system restart may not be required.

It's better to provide some log information for debugging more. and The piece of advice is you can try two or three versions of qemu-ga.msi and record the exact actions, which version has the situation you're describing, that‘ll be helpful.
