### ISSUE TITLE
Fedora 40 having issues in handling TSO and LSO for the VM using KVM hypervisor

### ISSUE THREAD

**Issue by Shamri04** [virtio-win/virtio-win-guest-tools-installer#67]
Hi All , 

After fedora 40 upgrade I am facing issues like photo or other large files are not get handled properly , TCP packets are get tig dropped, 
Seems LSO and TSO issues. I am facing this only in windows client .

OS version : Fedora 40
Kernel Version: 6.10.4-200.fc40.x86_64
Hypervisor: KVM

Can anyone please help

**Comment by YanVugenfirer** [comment]
Please check the discussion here https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1131

There is an issue with the Linux kernel.
