### ISSUE TITLE
Upgrade aware installer | Keep Network adapter IP address during upgrade

### ISSUE THREAD

**Issue by ejb1123** [virtio-win/virtio-win-guest-tools-installer#70]
**Is your feature request related to a problem? Please describe.**
When upgrading from 262 to 266 the Network adapter settings are not persistent

**Describe the solution you'd like**
When installing a version of virtio drivers on a system that already has virtio drivers installed. The installer should use the a custom upgrade logic to persist network driver setting.  

**Describe alternatives you've considered**
Just install the inf and iterate through the network drivers and point them to the new driver version.

Then remove the old driver version from the system

**Comment by heywji** [comment]
@ejb1123 Hi, You mentioned about two things here. Is this correct?
1. The network adapter settings are not persistent
2. Only one installer package needs to be installed.

Question one can be divided into two parts: IP and DNS configuration. The virtio-win-1.9.36-0.el9_3 package fixes everything that you can download from our RedHat repos. 
Refer: [RHEL-1860](https://issues.redhat.com/browse/RHEL-1860) DNS configuration is lost in Windows machines after upgrading the virtio-win drivers

**Comment by xiagao** [comment]
For the internal installer, it could keep the network adapter config(ip address and DHCP config) when updating drivers via the installer. 
@heywji Could you have a try with the upstream installer?
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/

**Comment by heywji** [comment]
> @ejb1123 Hi, You mentioned about two things here. Is this correct?
> 
> 1. The network adapter settings are not persistent
> 2. Only one installer package needs to be installed.
> 
> Question one can be divided into two parts: IP and DNS configuration. The virtio-win-1.9.36-0.el9_3 package fixes everything.
> 
> Or do you comment about keeping the original configuration when upgrading the installer?
> 
> I'm looking forward to you following up with more information.
> 
> Thank you, Wecom

I don't see any problem with the Community Edition. 

Test Steps:
1. Install two Win11.x64_64 26100 guest
2. Uninstall and delete the existing network driver 
3. Download [virtio-win-0.1.262-2](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.262-2/) and install it.
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/a3b87a26-6cde-485f-9196-675be6361d33" />

5. Set the static IP and DNS info.
6. Download [virtio-win-0.1.266-1](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.266-1/) and update the existing installer package.
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/4e991ae3-196b-4fe1-9363-87cd80f3ecfc" />

**Comment by ejb1123** [comment]
@heywji I have created and reproduced showing this works in  afresh test VM.
This might be related to the VMs I am using coming from  previous hypervisor.
